name: HungerGamesMixer
main: mc.lhq.HungerGamesMixer.HungerGamesMixer
version: 1.0
commands:
  kit:
    description: kit
    usage: /kit [kitname]
  stats:
    description: stats
    usage: /stats
  p:
    description: togglechat
    usage: /p